---
- name: Install prerequisites
  become: true
  shell: |
    apt install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common \
    git \
    docker \
    docker-compose \
    docker.io

- name: Remove old data
  become: true
  file:
    path: /home/vagrant/git/
    state: absent

- name: Create GIT folder
  become: true
  file:
    path: /home/vagrant/git/
    state: directory

- name: Clone github repository
  become: true
  shell: |
    cd /home/vagrant/git/
    git clone "https://github.com/deviceTRUST/democloud-docker-logging.git"

- name: Stop Docker container
  become: true
  shell: |
    cd /home/vagrant/git/democloud-docker-logging
    docker-compose rm --stop --force

- name: Create Docker container
  become: true
  shell: |
    cd /home/vagrant/git/democloud-docker-logging
    docker-compose up -d